version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: python run.py

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    command: ["npm", "run", "build"]
    volumes:
      - react-build:/app/dist
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - react-build:/usr/share/nginx/html
      - ./nginx/letsencrypt:/etc/letsencrypt:ro  # ✅ on monte le dossier complet
      - ./nginx:/var/www/certbot
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx:/var/www/certbot
    entrypoint: ""
    command: >
      sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"
    restart: unless-stopped

volumes:
  react-build:
